sudo: required
services:
  - docker

before_install:
  - docker build -t vyoung/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vyoung/react-test npm test

after_success:
  - docker build -t vyoung/multi-client ./client
  - docker build -t vyoung/multi-nginx ./nginx
  - docker build -t vyoung/multi-server ./server
  - docker build -t vyoung/multi-worker ./worker
